# Generated by Django 5.2.7 on 2025-10-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=200)),
            ],
        ),
    ]
