# Generated by Django 5.2.7 on 2025-11-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_studentcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course',
            new_name='course_id',
        ),
    ]
