# Generated by Django 5.2.7 on 2025-12-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_rename_course_studentcourse_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course_id',
            new_name='course',
        ),
    ]
