# Generated by Django 5.2.7 on 2025-12-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_rename_course_id_studentcourse_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='course',
            new_name='course_id',
        ),
    ]
